### ISSUE TITLE
Nextcloud Mail broken, messages not loading (Nextcloud 20.0.1/Mail 1.5.1)

### ISSUE THREAD

**Issue by Manu3l0us** [linuxserver/docker-nextcloud#165]
## Expected Behavior
When opening Mail app in NC, new mails are shown. This seems to be a known problem mit Alpine-based Docker images: https://github.com/nextcloud/mail/issues/3908

## Current Behavior
No mails shown, stuck loading

## Steps to Reproduce
1. Update to latest version of Nextcloud and Mail
2. Open Mail app (with Mail account set up)

## Environment
**OS:** Openmediavault/Debian Buster
**CPU architecture:** x86_64
**How docker service was installed:** Official Repo

Below the log entry from my instance when opening Mail

[PHP] Error: Error: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed at /config/www/nextcloud/apps/mail/lib/Address.php#70 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8, "iconv(): Wrong  ... d", "/config/www/nex ... p", 70, [])
 1. /config/www/nextcloud/apps/mail/lib/Address.php line 70
    iconv("UTF-8", "UTF-8//IGNORE", "*****.********@gmail.com")
 2. /config/www/nextcloud/apps/mail/lib/Address.php line 86
    OCA\Mail\Address->getEmail()
 3. /config/www/nextcloud/apps/mail/lib/AddressList.php line 100
    OCA\Mail\Address->jsonSerialize()
 4. <<closure>>
    OCA\Mail\AddressList->OCA\Mail\{closure}("*** sensitive parameters replaced ***")
 5. /config/www/nextcloud/apps/mail/lib/AddressList.php line 101
    array_map(Closure {}, ["*** sensitive parameter replaced ***"])
 6. /config/www/nextcloud/apps/mail/lib/Db/Message.php line 254
    OCA\Mail\AddressList->jsonSerialize()
 7. <<closure>>
    OCA\Mail\Db\Message->jsonSerialize()
 8. /config/www/nextcloud/lib/public/AppFramework/Http/JSONResponse.php line 73
    json_encode([OCA\Mail\Db\Mes ... }], 1)
 9. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 123
    OCP\AppFramework\Http\JSONResponse->render()
10. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\MessagesController {}, "index")
11. /config/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "index", OC\AppFramework\ ... {}, {action: null,_r ... "})
12. /config/www/nextcloud/lib/base.php line 1009
    OC\Route\Router->match("/apps/mail/api/messages")
13. /config/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /apps/mail/api/messages?mailboxId=95&limit=20
from 193.222.*.* by **** at 2020-11-03T14:50:21+00:00

**Comment by tfmm** [comment]
I can also confirm this issue. After submittiing a bug to nextcloud's mail repo, it is determined to likely be related to iconv missing / not working properly. 

Bug for NC Mail: https://github.com/nextcloud/mail/issues/3999
StackOverflow with more info: https://stackoverflow.com/questions/63746822/why-does-iconv-returns-empty-string-in-php7-4-fpm-alpine-docker/63747282#63747282

Working on testing a fix, and will submit a PR if I can get it working

**Comment by stavros-k** [comment]
I fixed it with the following script. There might be easier way out there. But this script i found somewhere (i dont really remember sorry) fixed it.

```
PHP_VER=$(php -v | grep ^PHP | cut -d' ' -f2) && \
BUILD_PACKAGES="wget build-base php7-dev" && \

apk add --no-cache --virtual .php-build-dependencies $BUILD_PACKAGES && \
apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ gnu-libiconv-dev && \
(mv /usr/bin/gnu-iconv /usr/bin/iconv; mv /usr/include/gnu-libiconv/*.h /usr/include; rm -rf /usr/include/gnu-libiconv) && \
mkdir -p /opt && \
cd /opt && \
wget https://secure.php.net/distributions/php-$PHP_VER.tar.gz && \
tar xzf php-$PHP_VER.tar.gz && \
cd php-$PHP_VER/ext/iconv && \
phpize && \
./configure --with-iconv=/usr && \
make && \
make install && \
mkdir -p /etc/php7/conf.d && \
#next command not needed in LSIO Docker
#echo "extension=iconv.so" >> /etc/php7/conf.d/iconv.ini && \

apk del .php-build-dependencies && \
rm -rf /opt/*
```

**Comment by tfmm** [comment]
Bumping so this doesn't get closed as the issue is still present, awaiting merge of linked PR.

**Comment by danielsteiner** [comment]
Are there any updates?

**Comment by rzrhome** [comment]
Same Problem here ...

**Comment by ageisen2000** [comment]
bumping. I am still experiencing this issue

**Comment by PeterSchols94** [comment]
Bumping. I am also experiencing this issue. Is anyone working on a fix?

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-nextcloud/pull/166

**Comment by danielsteiner** [comment]
> #166

Doesn’t work. I tried that yesterday and mail is still not working.

**Comment by j0nnymoe** [comment]
No, it explains what needs to be done/current status.

**Comment by stavros-k** [comment]
```
PHP_VER=$(php -v | grep ^PHP | cut -d' ' -f2) && \
BUILD_PACKAGES="wget build-base php7-dev" && \

apk add --no-cache --virtual .php-build-dependencies $BUILD_PACKAGES && \
apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ gnu-libiconv-dev && \
(mv /usr/bin/gnu-iconv /usr/bin/iconv; mv /usr/include/gnu-libiconv/*.h /usr/include; rm -rf /usr/include/gnu-libiconv) && \
mkdir -p /opt && \
cd /opt && \
wget https://secure.php.net/distributions/php-$PHP_VER.tar.gz && \
tar xzf php-$PHP_VER.tar.gz && \
cd php-$PHP_VER/ext/iconv && \
phpize && \
./configure --with-iconv=/usr && \
make && \
make install && \
mkdir -p /etc/php7/conf.d && \
#next command not needed in LSIO Docker
#echo "extension=iconv.so" >> /etc/php7/conf.d/iconv.ini && \

apk del .php-build-dependencies && \
rm -rf /opt/*
```

put the above in a script file in your `/config/custom-cont-init.d` directory. 
also make sure the `file.sh` is executable the permissions are enough

This works for me from NC19 through NC21

Lets hope next alpine version will have a fix from upstream!

**Comment by danielsteiner** [comment]
I did that, didn’t work for me. Also using edge packages was discussed previously and it was decided that edge packages won’t be included in the release image as there can be compatibility issues

**Comment by stavros-k** [comment]
> I did that, didn’t work for me. Also using edge packages was discussed previously and it was decided that edge packages won’t be included in the release image as there can be compatibility issues

Did it installed successfully? Does the docker log show any errors?
I read somewhere that it will be leaving edge on the next release, but until then i'm not sure.

**Comment by danielsteiner** [comment]
yes, altough i have manually executed the script. Will try it with the init script in a few minutes.

**Comment by ChristophWurst** [comment]
Does anyone know how the PR #166 and and Mail issue https://github.com/nextcloud/mail/issues/3999 could have possibly vanished? Those two were about the iconv issue on Alpine.

**Comment by Intenos** [comment]
I still have the issue with the latest docker image. Do I have to do something in addition instead of updating the docker image. I run the latest nextcloud version 20.0.5 and Mail App version 1.7.2.

**Comment by Thomasolicious** [comment]
I'm also having this issue on nextcloud 20.0.5 & mail 1.7.2. Should this be fixed in the latest nextcloud update or do we still need to apply the script suggested above?

**Comment by ChristophWurst** [comment]
There is nothing to fix in Nextcloud. The issue is that iconv is broken on some Alpine images. This has to be fixed on the OS level.

**Comment by aptalca** [comment]
Users claimed iconv from the edge repo worked. Edge repo was snapshot to alpine 3.13 a few days ago, which is what the latest nextcloud image is using

**Comment by jacob-swanson** [comment]
Pulling the latest image today (2021-01-18) did not fix the issue for me. Adding the script from @stavros-k worked. I'm guessing the new iconv package didn't make it in the release.

**Comment by stavros-k** [comment]
Could nextcloud is looking on a wrong path for iconv?

**Comment by tobbenb** [comment]
Alpine 3.13 does not have the libiconv package from the edge repo. The build time of the package in 3.13 is 2020-07-11. So 3.13 will not fix the problem until alpine updates their package, if that is the fix.

**Comment by aptalca** [comment]
Alpine does a snapshot of their edge repo when they release the next version. They don't rebuild each package, therefore the build dates look older than the alpine version release date.

**Comment by aptalca** [comment]
@ChristophWurst #177 should fix it by loading gnu iconv instead

**Comment by Intenos** [comment]
@aptalca 
I still have the issue unfortunately. Let´s see if it is the same with other users.

**Comment by aptalca** [comment]
Remove your email account and re-add it. It worked for me.

**Comment by Aaron-von-Awesome** [comment]
Docker Image: linuxserver/nextcloud:amd64-20.0.5-ls115
Nextcloud: 20.0.5
Mail App: 1.8.0

I also had to remove my email accounts and re-add, now everything is working again :smiley:

**Comment by Intenos** [comment]
It worked also for me. Thanks a lot!

**Comment by duckpuppy** [comment]
I'm still having to rebuild iconv using the script posted above on linuxserver/nextcloud:20.0.7-ls119 - is the merged fix above released?

**Comment by aptalca** [comment]
Make sure you recreate your container based on a newly pulled latest image

**Comment by ChristophWurst** [comment]
FYI we now also have a patch that avoids the problematic //IGNORE option if possible https://github.com/nextcloud/mail/pull/4453

**Comment by duckpuppy** [comment]
I did recreate the container from the new image... still have to execute the script above or I get issues with importing e-mails that contain emojis in the subject.

**Comment by duckpuppy** [comment]
I've done that as well.

**Comment by ChristophWurst** [comment]
Okay, usually the *wrong datetime* issue is an indication for missing 4 byte support. Please open a ticket at https://help.nextcloud.com/c/apps/mail/35 where we can discuss your issue.

**Comment by duckpuppy** [comment]
Sure, will do. Just to confirm things are correct, here's my DB info:

```
MariaDB [nextcloud]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_general_ci   |
+--------------------------+----------------------+
1 row in set (0.000 sec)
```

**Comment by AlexCloudDev** [comment]
Hi,
I'm experiencing this problem too, for at least a few months. I had hoped it would be sorted out with further updates, but after the release of the 21 major release i lost hope.

I'm on the latest nextcloud fpm-alpine image.
I checked inside the container alpine's version: It is 1.13.2.
Mail app is on latest 1.8.3.
My database fullfills all nextcloud requirements.

But i still get
_Error: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed at /var/www/html/custom_apps/mail/lib/Model/IMAPMessage.php#276_

So how can i fix it?

**Comment by aptalca** [comment]
that's not our image, you need to contact nextcloud
